server:
  port: 9000
spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql:///shiro?characterEncoding=utf-8
   username: root
   password: root
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

mybatis:
  mapper-locations: mapper/*.xml

